### ISSUE TITLE
Can I use this API?

### ISSUE THREAD

**Issue by aweirdwhale** [ToBiDi0410/IYoutube#1]
Hello !
I develop things for fun and I'm interested in your API, I found it on Npm because I want to control my music with a diy board using arduino. Can I use your API please and if yes, how can I use it, I didn't find any documentation :)
Thanks for reading :)
-A Weird Whale

**Comment by aweirdwhale** [comment]
actually I just want a way to pause/play, go next and previous a video, I don't know if it's possible w/ your API

**Comment by ToBiDi0410** [comment]
Hey, thanks for your interest. This API is used for fetching Video Information, Search Results and so on.
Examples can be found in the 'test' folder.

**I'm sorry, but it is not meant to control videos or music, so it likely doesn't fit your requirements**
